name: manual_triggered_peviitor.ro
on:
  workflow_dispatch:
    inputs:
      workload:
        description: 'Workload for JMeter test'
        required: true
        default: '10'
      runtime: 
        default: '100'
jobs:
  JMeter_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Give_my_code
        uses: actions/checkout@v4.2.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Insert_Test_Data_QA
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          apache-jmeter-5.6.3/bin/jmeter -n -Jthreads=${{ github.event.inputs.workload }} -Jrun=${{ github.event.inputs.runtime }} -t QA_INSERTJOBS.jmx -l result.jtl
      - name: Upload Results
        uses: actions/upload-artifact@v4.4.3
        with:
          name: jmeter-results
          path: result.jtl
  Auto_Test:
    runs-on: ubuntu-latest
    steps:
      - name: firtsstepYan
        run: |
          pwd
          ls
